name: IntegrationTest

on:
  workflow_dispatch:
  pull_request:
    branches:
      - int

permissions: read-all

jobs:
  integration-test:
    permissions:
      contents: read
    runs-on: ubuntu-20.04
    steps:
      - uses: nextlinux/harden-runner@v2.4.0
        with:
          allowed-endpoints: api.github.com:443
            github.com:443
            golang.org:443
            int.api.next-linux.systems:443
            objects.githubusercontent.com:443
            pipelines.actions.githubusercontent.com:443
            proxy.golang.org:443
            nextlinux-agent.s3.us-west-2.amazonaws.com:443
            storage.googleapis.com:443
            sts.us-west-2.amazonaws.com:443
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@424fc82d43fa5a37540bae62709ddcc23d9520d4
        with:
          go-version: 1.19
      - run: sudo go test -v
      - run: go build -ldflags="-s -w" -o ./agent
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@5fd3084fc36e372ff1fff382a39b10d03659f355
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - run: aws s3 cp ./agent s3://nextlinux-agent/refs/heads/int/agent --acl public-read
      - name: Integration test
        uses: docker://ghcr.io/nextlinux/integration-test/int:latest
        env:
          PAT: ${{ secrets.PAT }}
